### ISSUE TITLE
 Make the admin page to recommend caching WP core components and theme well known assets

### ISSUE THREAD

**Issue by delapuente** [mozilla/wp-offline-content#32] opened 2016-04-07 10:58 UTC
The admin page should recommend WP core components and CSS, fonts, scripts and images of the theme to cache by checking them by default while keeping all non recognized files as opt-in.

This is a UX proposal to check core components and well known assets by default.

**Comment by darkwing** [comment] 2016-04-07 20:38
Seems like a duplicate of #33

**Closed** 2022-01-20 15:25 UTC
Labels: ARCHIVED - http://mzl.la/ghe-archive
